apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sapp
  namespace: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8sapp
  template:
    metadata:
      labels:
        app: k8sapp
    spec:
      containers:
      - name: k8sapp
        image: 077414106691.dkr.ecr.ap-south-1.amazonaws.com/k8sapp:latest
        ports:
        - containerPort: 80apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sapp
  namespace: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8sapp
  template:
    metadata:
      labels:
        app: k8sapp
    spec:
      containers:
      - name: myapp
        image: 077414106691.dkr.ecr.ap-south-1.amazonaws.com/k8sapp:latest
        ports:
        - containerPort: 80
